area/api:
  - changed-files:
      - any-glob-to-any-file: api/**

area/app/controllers:
  - changed-files:
      - any-glob-to-any-file: app/src/app/Controllers/**

area/app/models:
  - changed-files:
      - any-glob-to-any-file: app/src/app/Models/**

area/app/views:
  - changed-files:
      - any-glob-to-any-file:
          - app/src/app/Views/**
          - app/src/app/Layouts/**

area/database:
  - changed-files:
      - any-glob-to-any-file: database/**

area/docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/.dockerignore"
          - "compose+(.yml|.test|.prod)"
          - "**/Dockerfile"

area/javascript:
  - changed-files:
      - any-glob-to-any-file:
          - "app/**/*.js"

area/routes:
  - changed-files:
      - any-glob-to-any-file:
          - app/src/app/Core/Router.php
          - app/src/routes/**

area/tests:
  - changed-files:
      - any-glob-to-any-file:
          - app/phpunit.xml.dist
          - "**/tests/**"

kind/dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/requirements**.txt"
          - "**/composer.+(json|lock)"
  - head-branch: '^dependabot\/'

kind/design:
  - changed-files:
      - any-glob-to-any-file:
          - .editorconfig

kind/feature:
  - head-branch: '^feat\/'

kind/bug:
  - head-branch: '^fix\/'

kind/improvement:
  - head-branch: '^refactor\/'
