version: "3.8"
services:
  api:
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.type==api
    environment:
      APP_NAME: ${APP_NAME}
      MARIADB_SERVER: database
      MARIADB_PORT: "3306"
      MARIADB_DB: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_pass
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      timeout: 5s
      interval: 5s
      retries: 5
    image: ghcr.io/projecte-urbantree/api:main
    ports:
      - mode: host
        target: 8000
        published: 8000
    secrets:
      - source: db_pass
  database:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.type==database
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      timeout: 5s
      interval: 10s
      retries: 5
    image: mariadb:lts
    secrets:
      - db_pass
      - db_root_pass
    user: root
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
  web:
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.type==web
    environment:
      APP_NAME: ${APP_NAME}
      DB_HOST: database
      DB_PORT: "3306"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS_FILE_PATH: /run/secrets/db_pass
      LOG_FILE_PATH: /var/www/html/storage/logs/app.log
    image: ghcr.io/projecte-urbantree/urbantree:main
    ports:
      - mode: host
        target: 8000
        published: 8000
    secrets:
      - source: db_pass
    volumes:
      - type: volume
        source: storage-data
        target: /var/www/html/storage
volumes:
  database-data: {}
  storage-data: {}
secrets:
  db_pass:
    external: true
  db_root_pass:
    external: true
