#
# This file defines the services that make up the application
# Each service is a container that runs a single process
# Each container is built from an image, according to the Dockerfile specified in the build section
# For more information, see: https://docs.docker.com/compose/compose-file/
#

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: dev123
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass
    ports:
      - "3306:3306"
    volumes:
      - "./docker/database/start-scripts:/docker-entrypoint-initdb.d"
    networks:
      - app-network

  apache:
    build:
      context: .
      dockerfile: ./docker/website/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "./src:/var/www/html"
    restart: always
    networks:
      - app-network
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: dev123
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mariadb

networks:
  app-network:
    driver: bridge