#
# This file defines the services that make up the application
# Each service is a container that runs a single process
# Each container is built from an image, according to the Dockerfile specified in the build section
# For more information, see: https://docs.docker.com/compose/compose-file/
#

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      target: development
    ports:
      - 8000:80
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - database-password
    environment:
      - APP_NAME=UrbanTree
      - DB_HOST=database
      - DB_NAME=urbantree
      - DB_USER=root
      - PASSWORD_FILE_PATH=/run/secrets/database-password
      - LOG_FILE_PATH=/var/www/html/storage/logs/app.log
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor
    entrypoint: /bin/sh -c "export DB_PASS=$(cat /run/secrets/database-password) && exec apache2-foreground"

  database:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    restart: always
    user: root
    secrets:
      - database-password
    networks:
      - app-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/database-password
      MYSQL_DATABASE: urbantree
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - database
    environment:
      PMA_HOST: database

networks:
  app-network:
    driver: bridge

volumes:
  vendor-data:
    driver: local

secrets:
  database-password:
    file: docker/secrets/database-password.txt
