#
# This file defines the services that make up the application
# Each service is a container that runs a single process
# Each container is built from an image, according to the Dockerfile specified in the build section
# For more information, see: https://docs.docker.com/compose/compose-file/
#

services:
  server:
    build:
      context: .
      target: development
    ports:
      - 8000:80
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - database-password
    environment:
      - APP_NAME=UrbanTree
      - DB_HOST=database
      - DB_NAME=urbantree
      - DB_USER=root
      - DB_PASS_FILE_PATH=/run/secrets/database-password
      - LOG_FILE_PATH=/var/www/html/storage/logs/app.log
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

  database:
    build:
      context: .
      target: database
    restart: always
    user: root
    secrets:
      - database-password
    networks:
      - app-network
    volumes:
      - ./docker/database/start-scripts/:/docker-entrypoint-initdb.d/
      #! Necessary for production ↓
      # - database-data:/var/lib/mysql
    #* This will store the database in memory, so it will be lost when the container is stopped
    #* Allows start-scripts to be run on each container start
    #! Necessary for development, remove in production ↓
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/database-password
      MYSQL_DATABASE: urbantree
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - action: rebuild
          path: ./docker/database

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    environment:
      PMA_HOST: database

networks:
  app-network:
    driver: bridge

volumes:
  database-data:

secrets:
  database-password:
    file: docker/secrets/database-password.txt
