name: 📟 Release to Sentry
description: Release a new version to Sentry

inputs:
  environment:
    description: The Sentry environment
    required: true
  projects:
    description: The Sentry project slug
    default: "urbantree api"
  version:
    description: The version to release
    required: true

runs:
  using: composite
  steps:
    # https://github.com/getsentry/action-release/tree/e769183448303de84c5a06aaaddf9da7be26d6c7
    - name: 📟 Release to Sentry
      uses: getsentry/action-release@e769183448303de84c5a06aaaddf9da7be26d6c7
      with:
        projects: ${{ inputs['projects'] }}
        environment: ${{ inputs['environment'] }}
        version: ${{ inputs['version'] }}
