# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 🌳 Continous Integration

run-name: 🌱 Checking integrity of the app

on:
  push:
    branches: ["**", "!main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  foundation:
    name: 🌱 Foundation setup
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      images: ${{ steps.filter.outputs.changes || '["all"]' }}
    steps:
      # https://github.com/actions/checkout/tree/11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # https://github.com/dorny/paths-filter/tree/de90cc6fb38fc0963ad72b210f1f284cd68cea36
      - name: 🔄 Detect changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/file-filters.yml

  build:
    name: 🏗️ Build
    needs: foundation
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#example-adding-configurations
      matrix:
        image: ${{ needs.foundation.outputs.images }}
        exclude:
          - image: all
        include:
          - image: urbantree
            context: ./app
          - image: api
            context: ./api
    permissions:
      contents: read
      packages: write
      attestations: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    with:
      context: ${{ matrix.context }}
      image: ${{ matrix.image }}
    secrets: inherit
