name: 🗃️ Report

run-name: 🗂️ Reporting coverage data to Codecov, and release to Sentry

on:
  workflow_call:
    inputs:
      environment:
        default: test
        type: string
      version:
        required: true
        type: string

jobs:
  upload:
    name: 🗂️ Upload reports
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#example-adding-configurations
      matrix:
        image: [urbantree, api]
    steps:
      # https://github.com/actions/checkout/tree/11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # https://github.com/actions/download-artifact/tree/fa0a91b85d4f404e444e00e005971372dc801d16
      - name: 📥 Download coverage data
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: ${{ matrix.image }}-coverage

      # https://github.com/getsentry/action-release/tree/e769183448303de84c5a06aaaddf9da7be26d6c7
      - name: 📟 Release to Sentry
        uses: ./.github/actions/release-sentry
        with:
          environment: ${{ inputs.environment }}
          projects: ${{ matrix.image }}
          version: ${{ inputs.version }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}

      # https://github.com/codecov/test-results-action/tree/9739113ad922ea0a9abb4b2c0f8bf6a4aa8ef820
      - name: 🧮 Upload test results to Codecov
        uses: codecov/test-results-action@9739113ad922ea0a9abb4b2c0f8bf6a4aa8ef820
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # https://github.com/codecov/codecov-action/tree/015f24e6818733317a2da2edd6290ab26238649a
      - name: 📈 Upload coverage to Codecov
        uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
